#define WIFI_SSID "YOUR SSID"
#define WIFI_PASSWORD "YOUR PASSPHRASE"

// MQTT Broker
#define MQTT_HOST IPAddress(192, 168, 1, x)
#define MQTT_PORT 1883
#define MQTT_USER "YOUR LOGIN"
#define MQTT_PWD "YOUR PASSWORD"
#define MQTT_TOPIC "TOPIC_TO_USE"
